
mapping = {
	'#'		: 'SYM',
	'$'		: 'SYM',
	'AFX'	: 'ADJ',
	'CC'	: 'CCONJ',
	'CD'	: 'NUM',
	'DT'	: 'DET',
	'EX'	: 'PRON',
	'FW'	: 'X',
	'HYPH'	: 'PUNCT',
	'IN'	: 'ADP',
	'JJ'	: 'ADJ',
	'JJR'	: 'ADJ',
	'JJS'	: 'ADJ',
	'LS'	: 'X',
	'MD'	: 'VERB',
	'NIL'	: 'X',
	'NN'	: 'NOUN',
	'NNP'	: 'PROPN',
	'NNPS'	: 'PROPN',
	'NNS'	: 'NOUN',
	'PDT'	: 'DET',
	'POS'	: 'PART',
	'PRP'	: 'PRON',
	'PRP$'	: 'DET',
	'RB'	: 'ADV',
	'RBR'	: 'ADV',
	'RBS'	: 'ADV',
	'RP'	: 'ADP',
	'SYM'	: 'SYM',
	'TO'	: 'PART',
	'UH'	: 'INTJ',
	'VB'	: 'VERB',
	'VBD'	: 'VERB',
	'VBG'	: 'VERB',
	'VBN'	: 'VERB',
	'VBP'	: 'VERB',
	'VBZ'	: 'VERB',
	'WDT'	: 'DET',
	'WP'	: 'PRON',
	'WP$'	: 'DET',
	'WRB'	: 'ADV',
	'-LRB-'	: 'PUNCT',
	'-RRB-'	: 'PUNCT',
	'.'		: 'PUNCT',
	'?'		: 'PUNCT',
	':'		: 'PUNCT',
	'\''	: 'PUNCT',
	'"'		: 'PUNCT',
	','		: 'PUNCT',
	':'		: 'PUNCT',
	'('		: 'PUNCT',
	')'		: 'PUNCT',
	'START'	: 'START',
	'END'	: 'END'
}


def map_tag(tag):
	if tag in mapping:
		return mapping[tag]
	else:
		return 'X'